# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: gcs-fuse-csi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcs-fuse-csi-driver
  template:
    metadata:
      labels:
        app: gcs-fuse-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccount: gcs-fuse-csi-controller-sa
      priorityClassName: csi-gcp-gcs-controller
      containers:
        - name: gcs-fuse-csi-driver
          image: gke.gcr.io/gcs-fuse-csi-driver
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--endpoint=unix:/csi/csi.sock"
            - "--controller=true"
            - "--enable-gcsfuse-profiles=true"
            - "--leader-election=true"
            - "--leader-election-namespace=$(CLOUDSTORAGECSI_NAMESPACE)"
            - "--cluster-location=$(CLUSTER_LOCATION)"
            - "--project-number=$(PROJECT_NUMBER)"
            - "--http-endpoint=:29633"
          ports:
            - containerPort: 29633
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 80Mi
          env:
            - name: CLOUDSTORAGECSI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: gcsfusecsi-profiles-config
                  key: cluster-location
            - name: PROJECT_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: gcsfusecsi-profiles-config
                  key: project-number
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
