# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  annotations:
    # Optional: Uncomment the following annotations to add custom bucket annotations and bypass the scanner.
    # gke-gcsfuse/bucket-scan-status: "override"             # Required for "override": Will bypass the scanner with custom results.
    # gke-gcsfuse/bucket-scan-num-objects: "42"              # Required for "override": Total number of objects in the bucket / directory.
    # gke-gcsfuse/bucket-scan-total-size-bytes: "123456789"  # Required for "override": Total size in bytes of the bucket / directory.
    # gke-gcsfuse/bucket-scan-hns-enabled: "true"            # Required for "override": "true" or "false" if HNS is enabled.
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcsfusecsi-inference
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: test-bucket
    volumeAttributes:
      # Optional: The timeout for the bucket scan operation before giving up and delivering
      # partial results. The default is 2m.
      # bucketScanTimeout: 2m 
      # Optional: The TTL for the the bucket scan operation. New PV / Pod creation events won't
      # trigger the scanner until at least this amount of time has passed since the previous
      # scan. The default is 168h (7 days).
      # bucketScanTTL: 168h
  mountOptions:
  - only-dir=/my-folder/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: my-pv
  storageClassName: gcsfusecsi-inference 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        gke-gcsfuse/volumes: "true"
        # Feature flag
        gke-gcsfuse/profiles: "true"
    spec:
      serviceAccountName: my-ksa
      containers:
      - name: my-container
        image: nginx:latest
        volumeMounts:
        - name: my-gcs-volume
          mountPath: "/data/gcs"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
      volumes:
      - name: my-gcs-volume
        persistentVolumeClaim:
          claimName: my-pvc
