# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcsfusecsi-training
provisioner: gcsfuse.csi.storage.gke.io
mountOptions:
  # TODO(urielguzman): Replace mount options with 'profile=aiml-training' when `enable-gcsfuse-profiles-internal` is implemented.
  - implicit-dirs
  - metadata-cache:negative-ttl-secs:0
  - metadata-cache:ttl-secs:-1
  # - read_ahead_kb=1024  # Disabled                        
  # Conditional if file cache is set:
  - file-cache:cache-file-for-range-read:true
  # Conditional if volume is read-only:
  - file-system:kernel-list-cache-ttl-secs:-1
parameters:
  workloadType: "training"
  skipCSIBucketAccessCheck: "true"
  gcsfuseMetadataPrefetchOnMount: "true"
  fuseFileCacheMediumPriority: "gpu:ram|lssd,tpu:ram,general_purpose:ram|lssd"
  fuseMemoryAllocatableFactor: "0.7"
  fuseEphemeralStorageAllocatableFactor: "0.85"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcsfusecsi-inference
provisioner: gcsfuse.csi.storage.gke.io
mountOptions:
  # TODO(urielguzman): Replace mount options with 'profile=aiml-inference' when `enable-gcsfuse-profiles-internal` is implemented.
  - implicit-dirs
  - metadata-cache:negative-ttl-secs:0
  - metadata-cache:ttl-secs:-1
  - read_ahead_kb=1024
  # Conditional if file cache is set:
  - file-cache:cache-file-for-range-read:true
  # Conditional if volume is read-only:
  - file-system:kernel-list-cache-ttl-secs:-1
parameters:
  workloadType: "inference"
  skipCSIBucketAccessCheck: "true"
  gcsfuseMetadataPrefetchOnMount: "true"
  fuseFileCacheMediumPriority: "gpu:ram|lssd,tpu:ram,general_purpose:ram|lssd"
  fuseMemoryAllocatableFactor: "0.7"
  fuseEphemeralStorageAllocatableFactor: "0.85"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcsfusecsi-checkpointing
provisioner: gcsfuse.csi.storage.gke.io
mountOptions:
  # TODO(urielguzman): Replace mount options with 'profile=aiml-checkpointing' when `enable-gcsfuse-profiles-internal` is implemented.
  - implicit-dirs
  - metadata-cache:negative-ttl-secs:0
  - metadata-cache:ttl-secs:-1
  - read_ahead_kb=1024
  # Conditional if file cache is set:
  - file-cache:cache-file-for-range-read:true
  # Conditional if volume is read-only:
  - file-system:kernel-list-cache-ttl-secs:-1
  # Conditional if using HNS:
  - file-system:rename-dir-limit:200000
parameters:
  workloadType: "checkpointing"
  skipCSIBucketAccessCheck: "true"
  gcsfuseMetadataPrefetchOnMount: "true"
  fuseFileCacheMediumPriority: "gpu:ram|lssd,tpu:ram,general_purpose:ram|lssd"
  fuseMemoryAllocatableFactor: "0.7"
  fuseEphemeralStorageAllocatableFactor: "0.85"
