# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gcs-fuse-csi-driver
resources:
- ../../base/setup
- ../../base/webhook
- ../../base/node
transformers:
- ../../images/stable
patches:
- path: project_patch_csi_driver.json
  target:
    group: storage.k8s.io
    kind: CSIDriver
    name: gcsfuse.csi.storage.gke.io
    version: v1
- path: caBundle_patch_MutatingWebhookConfiguration.json
  target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: gcsfuse-sidecar-injector.csi.storage.gke.io
    version: v1
- path: identity_provider_patch_csi_node.json
  target:
    group: apps
    kind: DaemonSet
    name: gcsfusecsi-node
    version: v1
- path: identity_pool_patch_csi_node.json
  target:
    group: apps
    kind: DaemonSet
    name: gcsfusecsi-node
    version: v1
- path: wi_node_label_check_patch.json
  target:
    group: apps
    kind: DaemonSet
    name: gcsfusecsi-node
    version: v1
- path: ./node_args.yaml
  target:
    group: apps
    kind: DaemonSet
    name: gcsfusecsi-node
    version: v1

